[package]
name = "gradient"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
futures-core = "0.3.31"
futures-util = "0.3.31"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = {version = "1.44.2", features = ["rt", "macros", "time"]}
zbus = "5.5.0"
